name: Build Aurora website
description: Build a website with the Aurora (https://github.com/capjamesg/aurora) static site generator.
color: purple

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install aurora-ssg
      - name: Build main site
        env:  
          SITE_ENV: ${{ secrets.AURORA_SITE_ENV }}  
        run: |
          aurora build
          
